dist: trusty
language: bash
cache:
  pip: true
  directories:
    - ~/miniconda
env:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if ! hash conda 2>/dev/null; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    rm -r ~/miniconda;
    bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a
  - if [ ! -d "$HOME/miniconda/envs/test-environment" ]; then
    conda create -q -n test-environment python=$PYTHON_VERSION;
    fi
  - source activate test-environment
  - pip install -U pip
  - pip install --progress-bar=off -r test-requirements.txt
  - # places the numpy stubs inside a stubs folder for mypy
  - rm -rf stubs
  - curl -LO https://github.com/numpy/numpy-stubs/archive/master.zip
  - unzip master.zip
  - mkdir -p stubs
  - mv numpy-stubs-master/numpy-stubs stubs/numpy
  - rm -rf numpy-stubs-master master.zip

script:
  - if [ $PYTHON_VERSION == "3.6" ]; then
    pip install -U black;
    make black_check;
    fi
  - make test

after_success:
  - codecov
