dist: trusty
language: bash
cache:
  pip: true
  directories:
    - ~/miniconda
env:
  - PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if ! hash conda 2>/dev/null; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    rm -r ~/miniconda;
    bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a
  - if [ ! -d "$HOME/miniconda/envs/test-environment" ]; then
    conda create -q -n test-environment python=$PYTHON_VERSION;
    fi
  - source activate test-environment
  - pip install -U pip
  - pip install --progress-bar=off -r test-requirements.txt

script:
    - make test

after_success:
    - codecov
